// Code generated by go-swagger; DO NOT EDIT.

package models2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ExtUserObjectRef user object ref
// swagger:model ExtUserObjectRef
type ExtUserObjectRef struct {
	ExtUser
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ExtUserObjectRef) UnmarshalJSON(raw []byte) error {
	_ = "STUB: not implemented"
	// AO0
	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ExtUserObjectRef) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// Validate validates this user object ref
func (m *ExtUserObjectRef) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ExtUserObjectRef) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ExtUserObjectRef) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
