// Code generated by go-swagger; DO NOT EDIT.

package models2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ExtUser user
// swagger:model ExtUser
type ExtUser struct {

	// age
	Age int64 `json:"age,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this user
func (m *ExtUser) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ExtUser) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *ExtUser) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
