// Code generated by go-swagger; DO NOT EDIT.

package models2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ExtUserObjectFlat user object flat
// swagger:model ExtUserObjectFlat
type ExtUserObjectFlat struct {

	// age
	Age int64 `json:"age,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this user object flat
func (m *ExtUserObjectFlat) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ExtUserObjectFlat) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ExtUserObjectFlat) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
