// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ExtUsersArrayRef users array ref
// swagger:model ExtUsersArrayRef
type ExtUsersArrayRef []*ExtUser

// Validate validates this users array ref
func (m ExtUsersArrayRef) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required
