// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ExtUsersArrayFlat users array flat
// swagger:model ExtUsersArrayFlat
type ExtUsersArrayFlat []*ExtUsersArrayFlatItems0

// Validate validates this users array flat
func (m ExtUsersArrayFlat) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// ExtUsersArrayFlatItems0 users array flat items0
// swagger:model ExtUsersArrayFlatItems0
type ExtUsersArrayFlatItems0 struct {

	// age
	Age int64 `json:"age,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this users array flat items0
func (m *ExtUsersArrayFlatItems0) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ExtUsersArrayFlatItems0) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ExtUsersArrayFlatItems0) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
